### ISSUE TITLE
Enable Sponsors for this repo?

### ISSUE THREAD

**Issue by tiesont** [fabricjs/fabricjs.github.io#11]
Hey there;

Would it be possible to enable Sponsors on this repo? I just starting sponsoring the library repo, and I'd like to do the same here as well, unless it's simpler to just double-down on my other sponsorship.

Thanks!

**Comment by asturur** [comment]
hi @tiesont , thanks for it first of all. Sponsoring is to devs and not to projects.

Maybe @nimworks can enter github sponsor program and i ll add him to the list here, he is driving the work for the new website.

**Comment by tiesont** [comment]
Now, if only _someone_ would get his Sponsors enrollment squared away...

**Comment by tiesont** [comment]
Also, I think I'm morally obligated to add this:


![fry](https://user-images.githubusercontent.com/420293/84753401-f346b100-af8c-11ea-811f-1a768a3a0e07.png)

**Comment by nimworks** [comment]
> Now, if only _someone_ would get his Sponsors enrollment squared away...

Yes, am on the wait list for getting enrolled in the program _(due to country constraints)_ 😇
Thanks
