### ISSUE TITLE
docs: how to style object controls globally in 6.0

### ISSUE THREAD

**Issue by asturur** [fabricjs/fabricjs.github.io#126]
### Discussed in https://github.com/fabricjs/fabricjs.github.io/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **sohailahmad07** July  5, 2024</sup>

i fabric js 5.3 this code was working but in 6.0 it not working any more how can i style the controls in 6.0 

**5.6**
```
  fabric.object.prototype.set({
                transparentCorners: false,
                cornerColor: "white",
                cornerStrokeColor: "white",
                borderColor: "white",
                cornerSize: 10,
                padding: 10,
                cornerStyle: "circle",
                borderDashArray: [3, 3]
            });
```

**6.0** Both code snippet are not working

```
  fabric.FabricObject.prototype.set({
                transparentCorners: false,
                cornerColor: "white",
                cornerStrokeColor: "white",
                borderColor: "white",
                cornerSize: 10,
                padding: 10,
                cornerStyle: "circle",
                borderDashArray: [3, 3]
            });
            
            ----- or ----
            // fabric object is imported 
            
            
              FabricObject.prototype.set({
                transparentCorners: false,
                cornerColor: "white",
                cornerStrokeColor: "white",
                borderColor: "white",
                cornerSize: 10,
                padding: 10,
                cornerStyle: "circle",
                borderDashArray: [3, 3]
            });
```</div>

**Comment by rakibatomnixima** [comment]
I'm also looking for a simple way to style the global controls.

**Comment by rakibatomnixima** [comment]
@asturur any progression on this?

**Comment by asturur** [comment]
https://github.com/fabricjs/fabricjs.github.io/pull/128/
Made this PR here. I'll merge then give me feedback on the explanations.

**Comment by asturur** [comment]
https://fabricjs.github.io/docs/configuring-controls/

Please post feedback here even with the closed issue

**Comment by rakibatomnixima** [comment]
Thanks a lot for the doc update. It's very easy to understand. I could find what I was looking for, and solve my issue by reading it once.

Just one issue on the example codes where cornerStyle is assigned twice on 'Configuring control defaults for every object' and 'Configuring control handles' sections.

**Comment by asturur** [comment]
If you have time open a PR to fix it.
