### ISSUE TITLE
Refer to the GitHub.io instead of existing FabricJS.com

### ISSUE THREAD

**Issue by talaviram** [fabricjs/fabricjs.github.io#139]
I see this is repo suggest this is a WIP.
However the current website lacks of 2 things:

1. It's not updated - many times googling I end up getting to http://www.farbicjs.com and discover things have changed.
2. It lacks HTTPS. this could easily be fixed by let's encrypt or free Cloudflare plan.

**Comment by asturur** [comment]
The content of this website needs to go over fabricJS.com
