### ISSUE TITLE
The event demo lacks text-related events

### ISSUE THREAD

**Issue by aswind7** [fabricjs/fabricjs.github.io#173]
Link:  https://fabricjs.com/demos/events-inspector/

Missing events include:
```
  'text:selection:changed': { target: IText };
  'text:changed': { target: IText };
  'text:editing:entered': { target: IText } & Partial<TEvent>;
  'text:editing:exited': { target: IText };
```

**Comment by asturur** [comment]
https://github.com/fabricjs/fabricjs.github.io/pull/176

Trying to finish this as quick as possible and then add a full page of general events introduction
