### ISSUE TITLE
Add directories & markdown files for demos

### ISSUE THREAD

**Issue by nimworks** [fabricjs/fabricjs.github.io#18]
Based off the [current website](http://fabricjs.com) write out content for each of the demo pages.
Directories for the demo pages are under [src/pages/demos directory](https://github.com/fabricjs/fabricjs.github.io/tree/development/src/pages/demo) and one can even refer some content which is already there 🤗 before writing out another demo page

In the markdown, include the **title**, **description** and the **thumbnail** as front-matter

**Comment by asturur** [comment]
@nimworks if this is manual work of conversion i can take some.
Let's make a PR per page, so is easier to review.
Is there any groundwork missing or can i already start?

**Comment by nimworks** [comment]
Ohh, that would be great, thanks @asturur  😇

Yes, this is manual work mostly involving the following steps

1. Refer the [demos page](http://fabricjs.com/demos) of current website for all demos
2. For each demo, make a directory under [src/pages/demo](https://github.com/fabricjs/fabricjs.github.io/tree/development/src/pages/demo) directory
3. Name each directory as per the demo. The name should be either **lower-case letters or numbers** & use **-** instead of whitespace between words. This name will b what will appear in the URL like so `website.com/demos/<the-demo-directory-name>`
4. Inside the directory for each of the demos, make **index.md** markdown file!
5. Copy over the text content from current website into this markdown file taking care of writing all sub-headers for each of topics as `## Some awesome topic`
6. In the markdown **front-matter**, mention the **title**, **description** & **thumbnail**
7. Thumbnail images could be downloaded from the current website and renamed appropriately _(for SEO purposes which we'd come to later)_. The downloaded thumbnail could be placed beside the **index.md** file we created in step-4

I have already placed some demos which u cud refer 🤗

Yeah, PR for each page would b good too or if that seems very repetitive maybe we could just split it into multiple commits on the same PR, just naming the commit appropriately using the demo name in it 😇

**Comment by asturur** [comment]
Going to try one asap!

**Comment by nimworks** [comment]
We'd continue adding new pages to the demos by referring to the current site!
For now I'd go ahead and create all the markdown pages for these Demos.
@AndreaBogazzi, we can later look into adding codePens to some demos that do not have em 😊

**Comment by asturur** [comment]
yes just copy pasting for now is enough, most are in html tho.
we can do i start from the oldest you start from the newest, and at some point we meet in the middle.

**Comment by nimworks** [comment]
> ... i start from the oldest you start from the newest, and at some point we meet in the middle.

By newest ones, you mean from the bottom of the list, right? 🤔

**Comment by asturur** [comment]
should be. They have date in front of them. From the bottom works too.

**Comment by nimworks** [comment]
Ohh, ok, yes in the [current website repo](https://github.com/fabricjs/fabricjs.com/tree/gh-pages/posts/demos/_posts) we have the dates! I wasn't actually able to find where the posts were initially and thus was referring to live website [demos page](http://fabricjs.com/demos/) for sourcing the content!

My bad, sry 😅
