### ISSUE TITLE
Create a component to display the carbonAd ad

### ISSUE THREAD

**Issue by asturur** [fabricjs/fabricjs.github.io#20]
Create a component that let us:

Display the add
Display the reminder if the ad is blocked

The ad should find a place in the top right corner, possibly in all pages.

**Comment by nimworks** [comment]
yes, later we'll look into how we can place the sponsored content without it being obstructive. Or maybe a option for user to hide/close the advert per page load! Helpful on mobile devices!
Also on a mobile device, the advert could be made inline with the main content instead of having it fixed.
