### ISSUE TITLE
Styling, readibility

### ISSUE THREAD

**Issue by asturur** [fabricjs/fabricjs.github.io#21]
We should improve contrast a bit, the text seems to me blurry and low contrast.

**Comment by nimworks** [comment]
Yes, this will be done in the optimization phase! We'll run it through **Light-House** auditing tool and it'll report all the errors and things requiring optimization in one go!

SEO, too, wud be worked on in the optimization phase!

For now, the aim 🎯 is to have a basic structure up so that content-writing can happen in parallel!
Once the structure is ready, we'd move onto the optimization phase of releasing the MVP 😇

**Comment by nimworks** [comment]
For each header-text, we'd be checking if it confirms with [WCAG AAA standard](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast) and for body-text.

For body-text I was aiming for **AA** with ratio of **6:1** _(which comes close to AAA)_ but we can always bump it up a bit into AAA

**Comment by asturur** [comment]
I know now we are adding just content, but i mean is enough to have black text instead of grey text on white brackground, while we get to the optimization phase.

Did you thought of material/ui? do you like it? or you prefer classic manual components and css styles?

I had a quick experience with MUI + JSS and it was awesome for me.

**Comment by nimworks** [comment]
As for having high-contrast text now! I totally agree 👍 😇
I'd ship it in the coming feature I'd submit which is a basic styling-setup for entire site from header text to body text to padding and margin!

We'll yes, using a off-the-shelf UI framework like Material UI is nice but it appears too generic and may interfere with the brand-identity and design language we intend to craft! Thus I plan on crafting the styling ourselves!

As for CSS, we could start with sit for its simplicity and later maybe look into frameworks if maintainability is a issue! Altho as for documentation website, I think once styling is in place, it would remain so for the most part in the life-span of the website while major contributions wud be towards the content 😊

**Comment by nimworks** [comment]
The CSS colors, sizing and all the visual aspects, however basic at this stage, are already being worked on in #17 . I'd make sure to perform the appropriate accessibility tests for this release! 😇

**Comment by asturur** [comment]
No there won't be any mantainability issue. the website does not need to be mantained that much once is up, new content added yes, but there is nothing to do that react components alone do not solve perfectly.

**Comment by asturur** [comment]
I see that the the website has a new logo.
Where did you take that from? did you design it?
I kind like the actual logo we have on github and around some places ( not all  )

**Comment by nimworks** [comment]
> 
> 
> I see that the the website has a new logo.
> Where did you take that from? did you design it?
> I kind like the actual logo we have on github and around some places ( not all )

Yes, the logo is a very early draft and it was designed from ground-up so as to adhere to the brand-new design language we intend to carve for FabricJS!

Although it was part of my initial efforts in brand-design for FabricJS, I haven't taken the logo design through all relevant brand-design processes owing to time-constraints although the aim for the logo was it to be simple, yet iconic in digital space!

The logo icon has the two characters, **F** and **J** 🤗

**Comment by nimworks** [comment]
> 
> 
> No there won't be any mantainability issue. the website does not need to be mantained that much once is up, new content added yes, but there is nothing to do that react components alone do not solve perfectly.

Yes, precisely
