### ISSUE TITLE
CarbonAd.js - Error with argument passed to Window.getComputedStyle()

### ISSUE THREAD

**Issue by nimworks** [fabricjs/fabricjs.github.io#27]
Hi @asturur , am receiving the following error when I navigate the demos using the previous and next post links _(which are at the bottom of each demo page)_

![carbonAddError](https://user-images.githubusercontent.com/19433018/85233361-39839080-b423-11ea-8bb5-1881d802604e.png)

**Comment by asturur** [comment]
oh ok let me check it, i m finishing something and i ll jump on it.

**Comment by nimworks** [comment]
@asturur please take your time 😇
Maybe this issue is similar to [ref.current returns null when ref returns current.div](https://github.com/facebook/react/issues/16665) issue!
