### ISSUE TITLE
Implement basic structure for home page

### ISSUE THREAD

**Issue by nimworks** [fabricjs/fabricjs.github.io#29]
This task would mainly involve putting in place a **basic structure** for the 🏠 **home page** which cud progressively be populated with actual content ✏️

**Comment by jordanliu** [comment]
An example of the library in use on the homepage would be neat

**Comment by nimworks** [comment]
Yes, apart form the many demos, we intend to have some eye catching live examples as part of the webpage, perhaps some animated graphics playing as a background of the facia/banner 🤗

Altho this might be somewhat later in the list coz initial thing would be to setup the basic structure for all components to seamlessly function 😊
It is still being worked on in #43
