### ISSUE TITLE
Setup source-code infra for API docs & customize-build functionality

### ISSUE THREAD

**Issue by nimworks** [fabricjs/fabricjs.github.io#35]
This task would roughly involve cloning of the [FabricJs library repo](https://github.com/fabricjs/fabricJs) into a directory! 

For generating the **API documentation**, it could have been cloned temporarily during **build-time** as part of CI workflow but need to check if the same code-base is required at **run-time** by the **customize-build** functionality to work!

Also, in the development environment, we might work with only a small subset of data from the cloned repo to speed up dev iterations

**Comment by asturur** [comment]
This Is really low priority.
The manual procedure we have today is still bereable since is a one time per release.
In the future we can look in to actions that trigger actions on different repo in the same org.

**Comment by nimworks** [comment]
Yes, for now manual process would do fine!

The thing I was looking for was if we needed the files maintained in another repo to sit within this repo and had this requirement been only at build-time, this could well have been automated with using git clone in the CI workflow

But in our case, from what I could infer from the current live website, we also require the FabricJs source for offering the **custom-build** functionality to the user

And other area I intended to setup was that we could have an option to either process a dummy-subset of this source or bypass it completely when *developing* _(gatsby develop)_ for quickly spinning up the env _(although this seems one-time)_

**Comment by nimworks** [comment]
@asturur Could you lemme know the manual process carried out for generating the JSDoc page on the current website? 😊

**Comment by asturur** [comment]
We run this js here:
https://github.com/fabricjs/fabricjs.com/blob/gh-pages/build_docs.js

jsdoc generates all the pages at once following a template stored here:
https://github.com/fabricjs/fabricjs.com/tree/gh-pages/jsdoc_template

This is how we get the HTML pages.
I understand now is not the same thing, but also we maybe do not care? is really the last problem, demos and articles are way more important.

**Comment by nimworks** [comment]
1. **Demo pages:** The infra has been set-up, now it's just matter of adding the demo pages while referring to the current website. _(I understand some demos lack CodePens)_
2. **Docs:** The guide docs infra is setup & now we can start writing out the contents of the guide page-by-page. _(BTW, atm, the guide pages have a flat hierarchy)_
3. **API:** The JsDoc based documentation for the FabricJs API. Even this would b good to have as part of the MVP

Pointers 1 & 2 are fairly straightforward & yes I'd just as well shift my attention to completing those as well

**Comment by nimworks** [comment]
Ohh, sry, my bad! 😇 I had initially thought that JSDoc goes through all JS source files of Fabric library to churn out the API docs.
Now it occurred to me that JSDoc only goes through a [single JS file](https://github.com/fabricjs/fabricjs.com/blob/gh-pages/lib/fabricjs) to churn out the API docs

**Comment by asturur** [comment]
@cesine are you good with JSDOCS templates? Here the idea would be:
- add jsdocs to the deps of this repo
- create a script that can fit the output of JSDOC in this website
- run the script manually for now

**Comment by john-raymon** [comment]
@asturur Is anyone ok with me rewriting this repo/docs with Next.js using Next.js with MDX pages, and jsdocs? MDX so that the docs can have interactive examples of canvases istead of screenshots as they are now.

**Comment by asturur** [comment]
Is there any reason why gatsby is not good enough? they seems pretty similar to me.
I'm ok as long as @nimworks is ok with it.
He started this whole new website, and while this is actually not progressing, i m not starting any rewrite without his agreement.

Docs can have interactive examples in the form of codepen embedded prefill anyway, right?

**Comment by john-raymon** [comment]
thank you for the prompt reply! Gatsby sounds good too, I have only used Next.js and haven't reached for Gatsby yet since it has the same pre-rendering feature although without the themes I think. 

@nimworks I'm open to building out a new repo if anything or this repo, whichever is easier if you're open to starting a whole new website.

You're right, the docs can have interactive examples embedded using something like a Codepen or Codesandbox iframe but it comes with the branding, styled elements of the service, instead of being in the context of the page using MDX, like this for example https://github.com/john-raymon/lite-react-UI-components/blob/main/docs/pages/text-field.mdx.

**Comment by nimworks** [comment]
Hello,

@john-raymon thank you soo much for your offer towards implementing the features u highlighted! Especially the use of MDX pages u mentioned and it has been already implemented (just have to push it towards this repo) in another similar project I'm part of. So I think we'd have that very functionality / flexibility withing this GatsbyJS dev site itself!


Following are already done for a similar closed-source project I am working on:
**1**. MDX pages for directly integrating React components
**2**. Paginated navigation that takes into consideration sub-topics (Having sub-topics for the documentation would make a better UX). Much like how it's on the Gatsby dev docs site at https://www.gatsbyjs.com/docs/
**3**. Contributing documentation (Geared towards devs contributing towards this site)

And yes @asturur  sry for it's been a long time of inactivity from my end! Would be back and rolling with this site for most of the things have already been developed for other closed-source documentation site project (No issues with proprietary content cause it would anyhow make it's way into open-source through my blog)

Would be happy to hear on what other aspects it could be improved just as well 😀
Thanks a lot

**Comment by nimworks** [comment]
Hi @john-raymon , implementation of MDX feature is underway and can be followed via #45 😊

**Comment by john-raymon** [comment]
@nimworks Sorry for the late reply! I'd love to help out if needed.

**Comment by nimworks** [comment]
@john-raymon extremely sorry for this late reply! Had to attain to an emergency!

Ohh that's very nice of you! I'd wire up MDX pages and then maybe you could look into making a component for demo!

Although from the UX standpoint, since devs already trust brands like CodePen and CodeSandBox, it's fine to have their branding in the live preview!

I'd also add some road-map To-Dos to the [project board](https://github.com/fabricjs/fabricjs.github.io/projects/1) so that everyone can understand what the eminent tasks are

**Comment by john-raymon** [comment]
Hope all is well. I'll get started on this tomorrow! Are we still doing Gatsby?

**Comment by asturur** [comment]
My personal preference is for doing things rather than refactor them.
I want to state that i understand that everyone of us works on this on the free time, for free. Working on the newest cool tech is more fun than on the previous one, i know that. Gatsby and NextJs outside maybe corporate scaling issues seems pretty much similar to me and i would really love to get this website done one day and that could give us more satisfaction than merging a pr of something than then isn't going to be finished.

Said so guys if you find a common ground you can remove me from the equation of preferences and do what you like more i ll just insert the content in the chosen framework

**Comment by nimworks** [comment]
Hi, yes @john-raymon , we'd stick with GatsbyJs since it satisfies all the needs of this project.

I understand there are preferential differences with different devs opting for different frameworks, but I think just like what @asturur mentioned, it'd b nice to look at aiming to sculpt something rather than bifurcate on what tool to sculpt with (gien that we already are holding 1 tool in hand which pretty much satisfies all our needs) 😊

**Comment by nimworks** [comment]
Hi all! I have been fighting failure in installing the **pngquant** dependence 😬🥴 as is [mentioned on SO](https://stackoverflow.com/questions/51278961/reactjs-pngquant-failed-to-build-make-sure-that-libpng-dev-is-installed)

Perhaps its Node version mismatch

**Comment by asturur** [comment]
what do we need to do with png-quant?

**Comment by nimworks** [comment]
No we don't have it as a direct dependence! It's used by image processing I guess _(for generating thumbnails etc)_ by these static site generators!

It's failing when I do `npm install` !

Downgrading node on my machine to earlier version should fix it for now I hope! I'd go over it this weekend
